"use client";

import { useState, useRef, useEffect } from "react";

interface Message {
  role: "user" | "assistant";
    content: string;
      isTyping?: boolean;
      }

      export default function ChatPage() {
        const [messages, setMessages] = useState<Message[]>([
            { role: "assistant", content: "root@apinya-secure-node:~# initializing secure session..." },
                { role: "assistant", content: "<@apinya> connection established. don't waste my time. [21:05:00]" }
                  ]);
                    const [input, setInput] = useState("");
                      const [loading, setLoading] = useState(false);
                        const chatEndRef = useRef<HTMLDivElement>(null);

                          const scrollToBottom = () => {
                              chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
                                };

                                  useEffect(() => {
                                      scrollToBottom();
                                        }, [messages, loading]);

                                          const sendMessage = async (e: React.FormEvent) => {
                                              e.preventDefault();
                                                  if (!input.trim() || loading) return;

                                                      const userMsg = input.trim();
                                                          setInput("");
                                                              
                                                                  const timeString = new Date().toLocaleTimeString('en-IN', { hour12: false });
                                                                      const newMessages = [...messages, { role: "user" as const, content: `guest@local:~$ ${userMsg} [${timeString}]` }];
                                                                          setMessages(newMessages);
                                                                              setLoading(true);

                                                                                  try {
                                                                                        const res = await fetch("/api/chat", {
                                                                                                method: "POST",
                                                                                                        headers: { "Content-Type": "application/json" },
                                                                                                                body: JSON.stringify({
                                                                                                                          messages: newMessages.map(m => ({
                                                                                                                                      role: m.role,
                                                                                                                                                  content: m.content.replace(/\[\d{2}:\d{2}:\d{2}\]/g, "").replace("guest@local:~$ ", "").trim()
                                                                                                                                                            }))
                                                                                                                                                                    }),
                                                                                                                                                                          });

                                                                                                                                                                                const data = await res.json();
                                                                                                                                                                                      const replyTime = new Date().toLocaleTimeString('en-IN', { hour12: false });

                                                                                                                                                                                            if (data.reply) {
                                                                                                                                                                                                    const fullReply = `<@apinya> ${data.reply} [${replyTime}]`;
                                                                                                                                                                                                            setMessages((prev) => [...prev, { role: "assistant", content: "", isTyping: true }]);
                                                                                                                                                                                                                    setLoading(false);

                                                                                                                                                                                                                            let currentText = "";
                                                                                                                                                                                                                                    let i = 0;
                                                                                                                                                                                                                                            const speed = 15; 
                                                                                                                                                                                                                                                    const typingInterval = setInterval(() => {
                                                                                                                                                                                                                                                              if (i < fullReply.length) {
                                                                                                                                                                                                                                                                          currentText += fullReply.charAt(i);
                                                                                                                                                                                                                                                                                      setMessages((prev) => {
                                                                                                                                                                                                                                                                                                    const updated = [...prev];
                                                                                                                                                                                                                                                                                                                  updated[updated.length - 1] = { role: "assistant", content: currentText, isTyping: true };
                                                                                                                                                                                                                                                                                                                                return updated;
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                        i++;
                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                              clearInterval(typingInterval);
                                                                                                                                                                                                                                                                                                                                                                                          setMessages((prev) => {
                                                                                                                                                                                                                                                                                                                                                                                                        const updated = [...prev];
                                                                                                                                                                                                                                                                                                                                                                                                                      updated[updated.length - 1] = { role: "assistant", content: fullReply, isTyping: false };
                                                                                                                                                                                                                                                                                                                                                                                                                                    return updated;
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, speed);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#000000', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height: '100dvh', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: '100vw',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: 'flex', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flexDirection: 'column', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontFamily: 'monospace',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              overflow: 'hidden',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    position: 'fixed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          top: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                left: 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Top Bar */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ padding: '10px 15px', borderBottom: '1px solid #331118', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '11px', flexShrink: 0, backgroundColor: '#000000', color: '#E66A7E' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div><b>ssh apinya@secure-node:~</b></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ opacity: 0.7 }}>AES-256</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Chat Area */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ flex: 1, overflowY: 'auto', padding: '15px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {messages.map((msg, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const isUser = msg.role === "user";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const getMessageColor = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isUser) return '#E66A7E'; // Red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (msg.content.includes("initializing") || msg.content.includes("decrypting")) return '#7D1300'; // Logs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return '#F07AE3'; // Pink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={index} style={{ wordBreak: 'break-word', fontSize: '13px', lineHeight: '1.5', color: getMessageColor() }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {msg.content}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {msg.isTyping && <span style={{ animation: 'blink 1s infinite', background: '#F07AE3', display: 'inline-block', width: '6px', height: '13px', marginLeft: '4px', verticalAlign: 'middle' }}></span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ color: '#7D1300', fontSize: '13px' }}>&gt; decrypting secure stream...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div ref={chatEndRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Input Box */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <form onSubmit={sendMessage} style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '12px 15px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderTop: '1px solid #331118', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: 'flex', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alignItems: 'center', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#000000',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          flexShrink: 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ marginRight: '8px', fontSize: '13px', color: '#E66A7E' }}>guest@local:~$</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setInput(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="type message..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  autoFocus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: '#E66A7E', fontFamily: 'monospace', fontSize: '13px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <style jsx global>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        html, body {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background-color: #000000 !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                overflow: hidden;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @keyframes blink { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0%, 100% { opacity: 1; } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    50% { opacity: 0; } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        